### ISSUE TITLE
ValueError: Invalid header value 'CertbotACMEClient/0.8.0

### ISSUE THREAD

**Issue by guillaumemolter** [Gandi/letsencrypt-gandi#10]
I'm on El Capitan. Fresh install of both Certbot and Gandi let's encrypt.

Was working well a couple of days ago.

`./letsencrypt-auto run --domains www.domain.com             --authenticator letsencrypt-gandi:gandi-shs                 --letsencrypt-gandi:gandi-shs-name "Personal WordPress MU"                 --letsencrypt-gandi:gandi-shs-vhost www.domain.com                  --letsencrypt-gandi:gandi-shs-api-key APIKEY`

Then I see see the blue screen asking me for my email address...and then:

`ValueError: Invalid header value 'CertbotACMEClient/0.8.0 (darwin 10.11.5\n) Authenticator/letsencrypt-gandi:gandi-shs Installer/letsencrypt-gandi:gandi-shs'`

_I have obfuscated my API key and domain on purpose_

**Comment by guillaumemolter** [comment]
@baloo https://github.com/certbot/certbot/issues/3120

**Comment by baloo** [comment]
@guillaumemolter ho! thanks for the heads up. I've struggle to reproduce but have been unable to. Still, I got a small fix for compability with certbot and letsencrypt.

I'm closing the issue then, feel free to reopen for follow up :)
