### ISSUE TITLE
Mac OS 10.11 and plugin install

### ISSUE THREAD

**Issue by cake17** [Gandi/letsencrypt-gandi#13]
Hello,

I'm trying to install the letsencrypt-gandi plugin and I can't find the way to install it.
I installed certbot with homebrew and I can't find the bin pip shell under `/.local/share/letsencrypt/bin/pip` nor under `/usr/local/Cellar/certbot/0.8.0/share/certbot`.

Is it possible to install this plugin easily with a Mac ?
Thanks in advance

**Comment by baloo** [comment]
I think homebrew should give you pip in your path, so you may just replace `~/.local/share/letsencrypt/bin/pip` with `pip`.

**Comment by cake17** [comment]
Thanks for your answer. I did the pip install so this installed the plugin.

Now I ran:

```
certbot run --domains www.my-vhost-name.com \
            --authenticator letsencrypt-gandi:gandi-shs \
            --letsencrypt-gandi:gandi-shs-name my-instance-name \
            --letsencrypt-gandi:gandi-shs-vhost www.my-vhost-name.com \
            --letsencrypt-gandi:gandi-shs-api-key xxxxxxx \
            --installer letsencrypt-gandi:gandi-shs`
```

and I get this error:

```
certbot: error: unrecognized arguments: --letsencrypt-gandi:gandi-shs-name my-instance-name--letsencrypt-gandi:gandi-shs-vhost www.my-vhost-name.com --letsencrypt-gandi:gandi-shs-api-key xxxxxx
```

Any idea ?

**Comment by baloo** [comment]
Looks like certbot doesn't look in the system path.

Can you give me the output of:

```
ls ~/.local/share/letsencrypt/bin/pip
```

**Comment by cake17** [comment]
No such file or directory

**Comment by cake17** [comment]
and with `pip list`
I get `letsencrypt-gandi (0.0.1.dev0, /Users/my-name/sites/outils/letsencrypt-gandi)`

**Comment by baloo** [comment]
I will try to find a mac, but I don't have access to one right now.

**Comment by cake17** [comment]
@baloo Thanks a lot !

**Comment by bcien** [comment]
I did use the same procedure as @cake17 to install cerbot and the gandi plugin on a mac, and did not work for me as well. I get the exact same error.
It seems like certbot isn't finding the gandi plugin with dynamic discovery of plugins through the setuptools entry points.
@baloo: If you need to run some commands on a mac I can gladly run them for you. In case you have a general idea what it might be, we may be able to investigate further if you give us an idea where to start looking. 
A workaround for mac users at the moment may be to run a compatible operating system in a virtual machine like VirtualBox.

**Comment by cake17** [comment]
ping @baloo Can we help you try something to fix this ?

**Comment by webcracy** [comment]
@cake17 @bcien We haven't been able to find an elegant way to do this yet, but #15 includes instructions to use the plugin when certbot was installed with Homebrew.

**Comment by baloo** [comment]
Documented in readme by @webcracy. I'm closing this issue. feel free to reopen :)

**Comment by cake17** [comment]
@webcracy @baloo  thanks for your help, this seems to work now !! 👍

**Comment by bcien** [comment]
Thanks @webcracy @baloo for the fix and @cake17 for the confirmation. It worked for me too. Just don't forget to specify the certbot config file with rsa-key-size = 2048 and not 4096, as Gandi Simple Instances are not compatible with 4096 keys.
It may be good to add a comment in the readme the change for renewal of certificates: 'certonly' instead of 'run'.
Now, let's encrypt ;)
