### ISSUE TITLE
Way too complicated: Just provide a checkbox for this in the Simple Hosting admin pages

### ISSUE THREAD

**Issue by gerdneuman** [Gandi/letsencrypt-gandi#21]
I am a happy Gandi Simple Hosting costumer. I appreciated your efforts, but this is not working for me. I'll stay with the yearly Comodo reseller cert for now! This is all way too complicated. Also one would have to repeat it every 3 months (or do some scripting) to get this.

I cannot find any roadmap on what gandi has planned regarding Let's Encrypt integration. I hope this plugin here is not the full answer.

Ideally, you would just have a checkbox on the Simple Hosting admin pages with

> [x] Enable https (with Let's Encrypt) for all domains linked to this Simple Hosting instance

And then all the rest is handled in the background with no need for me as a customer to do all the dirty, time consuming and errorprone work. That's how other providers do it.

**Comment by baloo** [comment]
Duly noted and I can confirm this is on our road-map. Not the right place, therefor closing.

**Comment by baloo** [comment]
Duly noted and I can confirm this is on our road-map. Not the right place, therefor closing.

**Comment by baloo** [comment]
Duly noted and I can confirm this is on our road-map. Not the right place, therefor closing.
