### ISSUE TITLE
Unable to renew (or create) new certificate 

### ISSUE THREAD

**Issue by mlecoq** [Gandi/letsencrypt-gandi#23]
```
Hi,
```

I have create a certificate on letsencrypt and I have to renew it tomorrow.

I am no more able to create or renew certificate. The only message I have is _Permission denied (publickey,password)_

┌──────────────────────────────────────────────────────────────────────┐
                                                                    │ Saving debug log to /var/log/letsencrypt/letsencrypt.log             │  
                                                                    │ _api_key_from_args                                                   │  
                                                                    │ Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org      │  
                                                                    │ Obtaining a new certificate                                          │  
                                                                    │ Performing the following challenges:                                 │  
                                                                    │ http-01 challenge for xxxxxxxx                            │  
                                                                    │ Deploying Certificate -Vp4mkIQnPQ7_-7ictjkgEdKYKA3Gb71qUJGUpalp5U:   │  
                                                                    │ -Vp4mkIQnPQ7_-7ictjkgEdKYKA3Gb71qUJGUpalp5U.xP6PExgDqH9XBFOFOrCiNlr4 │  
                                                                    │ LvadIW7WINlVhs-eZs4                                                  │  
                                                                    │ tmpfile = (8, '/tmp/tmpDcCbVT.letsencrypt.gandi.shs')                │  
                                                                    │ sftp ['sftp', '-o',                                                  │  
                                                                    │ 'UserKnownHostsFile=/Users/xxxx/.ssh/known_hosts',           │  
                                                                    │ 'xxx@xxxx.net']                                         │  
                                                                    │ sftp ['sftp', '-b', '-', '-o',                                       │  
                                                                    │ 'UserKnownHostsFile=/Users/xxxx/.ssh/known_hosts',           │  
                                                                    │ 'xxx@xxxx.net']                                         │  
                                                                    │ Cleaning up challenges                                               │  
                                                                    │ sftp ['sftp', '-b', '-', '-o',                                       │  
                                                                    │ 'UserKnownHostsFile=/Users/mickaellecoq/.ssh/known_hosts',           │  
                                                                    │ 'xxxx@xxxx.net']                                         │  
                                                                    └──────────────────────────────────────────────────────────────────────┘  

Permission denied (publickey,password).
Connection closed
Couldn't place file in domain: vhosts/xxxx/htdocs/.well-known/acme-challenge

**Comment by webcracy** [comment]
Hi there,

This error is usually related to an incomplete SSH authentication configuration. Have you setup SSH key authentication on your instance? And, if so, have you added the key to `ssh-agent`?  

Please take a look at the following sections of the README, they should provide the information you need to fix the issue:
- https://github.com/Gandi/letsencrypt-gandi#requirements-1
- https://github.com/Gandi/letsencrypt-gandi#authentication-issues 

Otherwise, please reopen this issue and let us know what went wrong.

**Comment by mlecoq** [comment]
One point for you ;)

I missed ssh-add step
