### ISSUE TITLE
Doesn't work - unrecognized arguments

### ISSUE THREAD

**Issue by DotSlashNatalie** [Gandi/letsencrypt-gandi#3]
This is the command I run from the instructions and the following output:

```
./letsencrypt-auto run --domains mydomain.com --authenticator letsencrypt-gandi:gandi-shs --letsencrypt-gandi:gandi-shs-name INSTANCE_NAME --letsencrypt-gandi:gandi-shs-vhost mydomain.com --letsencrypt-gandi:gandi-shs-api-key TEST_KEY --installer letsencrypt-gandi:gandi-shs
```

( Obviously values have been changed to protect the innocent )

Resulting output:

```
letsencrypt: error: unrecognized arguments: --letsencrypt-gandi:gandi-shs-name INSTANCE_NAME --letsencrypt-gandi:gandi-shs-vhost mydomain.com --letsencrypt-gandi:gandi-shs-api-key TEST_KEY
```

**Comment by papposilene** [comment]
Same problem here : unrecognized arguments and no solution found...

**Comment by webcracy** [comment]
@papposilene @nadams810 Can you please confirm that you have installed the plugin following these instructions: https://github.com/Gandi/letsencrypt-gandi#installation ?

If it's the case, please try to identify the location where the plugin binary was installed and compare it to the location of `letsencrypt-client`.

**Comment by papposilene** [comment]
I work on Mac, so : 
- /Users/MyAccount/letsencrypt/ and installation with instructions from [https://letsencrypt.org/getting-started/](https://letsencrypt.org/getting-started/).
- /Users/MyAccount/letsencrypt/letsencrypt_gandi/ and installation with instructions from [https://github.com/Gandi/letsencrypt-gandi#installation](https://github.com/Gandi/letsencrypt-gandi#installation)

**Comment by thekamaster** [comment]
@papposilene De mon côté j'ai eu droit à la même erreur (OS X également), mais j'avait installé le plugin en lançant pip directement (celui installé par Homebrew quand on installe le client letsencrypt) et non pas le pip inclus avec letsencrypt. Ca a beaucoup mieux marché avec ce dernier (avec le chemin comme indiqué dans la doc).

**Comment by thekamaster** [comment]
@papposilene I had the same issue on OS X, but I installed the gandi plugin with the pip installed by Homebrew (when first launching the letsencrypt client). Installing the plugin with the pip inside ~/.local/share/letsencrypt/bin/ as written in the gandi's instructions worked.
