### ISSUE TITLE
Plugin tries to remove the htdocs directory

### ISSUE THREAD

**Issue by thekamaster** [Gandi/letsencrypt-gandi#5]
After running the letsencrypt client, the last action made by the gandhi plugin is to remove temporary directories : 

```
sftp> rmdir vhosts/<myvhost>/htdocs//.well-known/acme-challenge
sftp> rmdir vhosts/<myvhost>/htdocs//.well-known/
sftp> rmdir vhosts/<myvhost>/htdocs//
Couldn't remove directory: Failure
```

I think the last one shouldn't be there ? (even if it fails)

**Comment by baloo** [comment]
That's kind of intended. We just issue commands to sftp. I didn't wanted to put pexpect or similar tools.

We try to create hierarchy of directories for the well-known secret to be available. We then remove all "potentially created" directories. We explicitly ignore the failure of those commands (which will fail if directory is not empty, which means it was there before and not empty).
