### ISSUE TITLE
Couldn't place "//.well-known/acme-challenge" file in domain

### ISSUE THREAD

**Issue by papposilene** [Gandi/letsencrypt-gandi#6]
Hi everyone, 

I followed every steps to install the Let's Encrypt Gandi plugin. Its works, until the installation on the server. I don't seem to have authentication issues (I can connect to my sftp through my OS X terminal and the `ssh -vvv user@gpaas` command shows that my SSH keys are accepted). But, I still have the same error (with or without the `sudo` command) : 

```
Connected to sftp.dc2.gpaas.net.
sftp> exit
Permission denied (publickey,password).
Connection closed
Permission denied (publickey,password).
Connection closed
Permission denied (publickey,password).
Connection closed
Couldn't place file in domain: vhosts/example/htdocs//.well-known/acme-challenge
```

Is there anyone who would have faced the same problem and have a solution?
Thanks a lot ! :)

**Comment by azediv** [comment]
Hi @papposilene 

On OS X, in `/etc/sudoers` section  `Defaults specification` , I added this line 

`Defaults env_keep+=SSH_AUTH_SOCK`

Then comand run without error with current user.

Hope it helps !

**Comment by papposilene** [comment]
Unfortunately this line is already present in my file `/etc/sudoers`. :(

**Comment by xfra35** [comment]
Same problem here, although I ran the script from a Gandi Debian vm:

```
Connected to sftp.dc0.gpaas.net.
sftp> exit
Permission denied (publickey,password).
Couldn't read packet: Connection reset by peer
Permission denied (publickey,password).
Couldn't read packet: Connection reset by peer
Permission denied (publickey,password).
Couldn't read packet: Connection reset by peer
Couldn't place file in domain: vhosts/xxx/htdocs//.well-known/acme-challenge
```

I finally had to bypass the Gandi plugin and to generate the certificate in manual mode (`letsencrypt certonly --manual`).

**Comment by coreygo** [comment]
Created a pull request which solved this by removing the '-b', '-' options. Might just be the extra empty dash option but didn't test that scenario after the plugin worked correctly.

**Comment by stanfaire** [comment]
Hello ! I did update SHS.py file, but I get the same results  :

`sftp ['sftp', '-o', 'UserKnownHostsFile=/Users/Stan/.ssh/known_hosts', 
Connected to sftp.dc2.gpaas.net.

Permission denied (publickey,password).
Connection closed
Cleaning up challenges
Permission denied (publickey,password).
Connection closed
Permission denied (publickey,password).
Connection closed
Couldn't place file in domain: vhosts/wearefrauds.com/htdocs//.well-known/acme-challenge`
