### ISSUE TITLE
Upstream rename from letsencrypt -> certbot

### ISSUE THREAD

**Issue by pde** [Gandi/letsencrypt-gandi#7]
Hi,

I'm the lead dev on the upstream letsencrypt client, which is about to be renamed to "certbot" tomorrow.  It would be good if the `letsencrypt-gandi` team could check for any breakage (in _theory_ there shouldn't be any, but we did get one report here: https://github.com/certbot/certbot/issues/2957).

When Certbot launches, it will have a nifty website that asks the user to pick their OS and webserver, and provides simple instructions in response. If the `letsencrypt-gandi` team would like to add some instructions for their plugin, please send us a PR with instructions [here](https://github.com/certbot/website/tree/master/_scripts/instruction-widget/templates/getting-started) (HTML + mustache) and hooks [here](https://github.com/certbot/website/blob/master/_scripts/instruction-widget/get-started.js).

(That repo will be public tomorrow, but I've invited you in the mean time).

**Comment by baloo** [comment]
Hi @pde,
Thanks for the notification. We will have a look into it.

**Comment by emory** [comment]
Please do look into it, @baloo :)

**Comment by baloo** [comment]
Fixed.
