### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pikurasa** [Gandi/letsencrypt-gandi#8]
> ~/letsencrypt-gandi $ ~/.local/share/letsencrypt/bin/pip install -e .

I think this is suppose to be

$ ~/.local/share/letsencrypt/bin/pip install -e ~/letsencrypt-gandi

I tried the above and it didn't work (doesn't make sense either). Bottom worked.

**Comment by baloo** [comment]
have you changed your directory (`cd`) before issuing the command?
All the commands in the installation section are intended to be used. Unfortunately we can't change it to `~/letsencrypt-gandi` because we can't make assumptions on where you will clone the project.

**Comment by baloo** [comment]
See https://github.com/Gandi/letsencrypt-gandi#installation

**Comment by pikurasa** [comment]
I already installed it correctly, so I do not need instructions on how to do it.

However, that is why I think there may be a typo on your page.

When you put in the following as a command, it works:

~/.local/share/letsencrypt/bin/pip install -e ~/letsencrypt-gandi

However, this does not (this is what you have on your page):

~/.local/share/letsencrypt/bin/pip install -e

(It doesn't have the last part of the argument)

Please verify.

**Comment by baloo** [comment]
Well the ending `.` in `~/.local/share/letsencrypt/bin/pip install -e .` is not a typo, and you are expected to use it. If you do not put an ending `.` then yes, it is not expected to work. It is very similar to `~/.local/share/letsencrypt/bin/pip install -e $(PWD)`.

**Comment by pikurasa** [comment]
Okay, I get it now. Maybe I am the only one who would read this incorrectly, but I did not find this very obvious. If you find that additional clarity is needed for others, what you say above about PWD is probably enough to make it clear (i.e. that the dot is intended to install to the current directory). Thanks again!
