### ISSUE TITLE
Requested domain vhost is not a FQDN

### ISSUE THREAD

**Issue by t-bo** [Gandi/letsencrypt-gandi#9]
Hi,

This is error I get: "Requested domain vhost is not a FQDN".

My domain vhost is normally showing in my Gandi instance, so I don't understand.

And it's actually doing it with any domain vhost I put here:
                --letsencrypt-gandi:gandi-shs-vhost toto.tld \

**Comment by baloo** [comment]
Can you paste the full command ?

**Comment by t-bo** [comment]
My bad I forgot to replace VHOSTS by the domain in first line.
But now I'm facing with a **unrecognized arguments**

> ./letsencrypt-auto run --domains domain.tld \
>             --authenticator letsencrypt-gandi:gandi-shs \
>                 --letsencrypt-gandi:gandi-shs-name domain.tld \
>                 --letsencrypt-gandi:gandi-shs-vhost domain.tld \
>                 --letsencrypt-gandi:gandi-shs-api-key xxxxxxxxx  \
>             --installer letsencrypt-gandi:gandi-shs
> usage: 
>   letsencrypt-auto [SUBCOMMAND] [options] [-d domain] [-d domain] ...

......
**letsencrypt: error: unrecognized arguments: --letsencrypt-gandi:gandi-shs-name mysimple --letsencrypt-gandi:gandi-shs-vhost domain.tld --letsencrypt-gandi:gandi-shs-api-key xxxxxxxxxxx**

**Comment by t-bo** [comment]
Ok I reinstalled the script once again with the pip command, and it worked!
